"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import json
import os
import re
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env', override=False)


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {'true', '1', 'yes', 'on'}:
        return True
    if normalized in {'false', '0', 'no', 'off'}:
        return False
    raise ImproperlyConfigured(f'{name} debe ser un booleano valido.')


def env_list(name, default=''):
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


# ---------------------------------------------------------
# SECURITY
# ---------------------------------------------------------

SECRET_KEY = os.getenv('SECRET_KEY', '').strip()
if not SECRET_KEY:
    raise ImproperlyConfigured('Configura SECRET_KEY en backend/.env o en el entorno.')

ENVIRONMENT = os.getenv('ENVIRONMENT', 'production').strip().lower()
DEBUG = env_bool('DJANGO_DEBUG', ENVIRONMENT in {'l', 'local', 'dev', 'development'})

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1' if DEBUG else '')


# ---------------------------------------------------------
# APPLICATIONS
# ---------------------------------------------------------

INSTALLED_APPS = [
    # Django
    'config.admin.RegistroAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'corsheaders',

    # Local
    'agenda',
    'usuarios',
    'roles',
]

AUTH_USER_MODEL = 'usuarios.User'


# ---------------------------------------------------------
# MIDDLEWARE
# ---------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # CORS debe estar antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ---------------------------------------------------------
# URLS
# ---------------------------------------------------------

ROOT_URLCONF = 'config.urls'


# ---------------------------------------------------------
# TEMPLATES
# ---------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# ---------------------------------------------------------
# DATABASE
# ---------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# ---------------------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------------

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------
# STATIC FILES
# ---------------------------------------------------------

STATIC_URL = 'static/'


# ---------------------------------------------------------
# DEFAULT PRIMARY KEY
# ---------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------
# CORS
# ---------------------------------------------------------

CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', True)
CORS_ALLOW_HEADERS = (*default_headers, 'idempotency-key')

# ---------------------------------------------------------
# DJANGO REST FRAMEWORK
# ---------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'usuarios.authentication.LocalJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
}


# ---------------------------------------------------------
# API KEYS
# ---------------------------------------------------------

try:
    AGENDA_API_KEYS = json.loads(os.getenv('AGENDA_API_KEYS', '{}'))
except json.JSONDecodeError as exc:
    raise ImproperlyConfigured('AGENDA_API_KEYS debe ser un objeto JSON valido.') from exc
if not isinstance(AGENDA_API_KEYS, dict) or any(
    not isinstance(key, str) or not key.strip() or not isinstance(value, str) or not value.strip()
    for key, value in AGENDA_API_KEYS.items()
):
    raise ImproperlyConfigured('AGENDA_API_KEYS debe mapear claves no vacias a nombres de sistemas.')

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', ','.join(CORS_ALLOWED_ORIGINS))

# Credenciales de integraciones: la identidad y los permisos vienen del backend.
try:
    EXPEDIENTES_API_KEYS = json.loads(os.getenv('EXPEDIENTES_API_KEYS', '{}'))
except json.JSONDecodeError as exc:
    raise ImproperlyConfigured('EXPEDIENTES_API_KEYS debe ser un objeto JSON valido.') from exc
if not isinstance(EXPEDIENTES_API_KEYS, dict):
    raise ImproperlyConfigured('EXPEDIENTES_API_KEYS debe ser un objeto JSON.')
for key, config in EXPEDIENTES_API_KEYS.items():
    if (
        not isinstance(key, str) or not key.strip() or not isinstance(config, dict)
        or not isinstance(config.get('sistema'), str)
        or not re.fullmatch(r'[A-Za-z0-9_]{1,80}', config['sistema'].strip())
        or not isinstance(config.get('permisos'), list)
        or not all(isinstance(value, str) for value in config['permisos'])
        or not set(config['permisos']).issubset({'reservar', 'consultar'})
    ):
        raise ImproperlyConfigured('Cada credencial de expedientes requiere sistema y permisos reservar/consultar.')
for sistema in AGENDA_API_KEYS.values():
    if not re.fullmatch(r'[A-Za-z0-9_]{1,80}', sistema.strip()):
        raise ImproperlyConfigured('El codigo de sistema de AGENDA_API_KEYS no es valido.')

# Configuracion compartida con el portal.
PORTAL_SIGNING_KEY = os.getenv('SIGNING_KEY', '').strip()
if not PORTAL_SIGNING_KEY:
    raise ImproperlyConfigured('Configura SIGNING_KEY para validar los tokens del portal.')
PORTAL_SYSTEM_CODE = os.getenv('PORTAL_SYSTEM_CODE', '').strip().lower()
if not PORTAL_SYSTEM_CODE:
    raise ImproperlyConfigured('Configura PORTAL_SYSTEM_CODE con el codigo registrado en el portal.')
PORTAL_DEFAULT_ROLE = os.getenv('PORTAL_DEFAULT_ROLE', 'CONSULTOR').strip().upper()
if PORTAL_DEFAULT_ROLE not in {'CONSULTOR', 'ADMINISTRATIVO', 'ADMINISTRADOR'}:
    raise ImproperlyConfigured('PORTAL_DEFAULT_ROLE no es un rol de Agenda DPA.')
SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': PORTAL_SIGNING_KEY,
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}
PORTAL_AUTO_ENABLE_USERS = env_bool('PORTAL_AUTO_ENABLE_USERS', False)
