# Generated by Django 5.2.17 on 2026-10-06 14:47

import agenda.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativoAnual',
            fields=[
                ('anio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('anio', models.PositiveSmallIntegerField(default=agenda.models.anio_actual, editable=False)),
                ('letra', models.CharField(blank=True, default='', max_length=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('causante', models.CharField(blank=True, default='', max_length=255)),
                ('asunto', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('origen', models.CharField(editable=False, max_length=100)),
                ('sistema_origen', models.CharField(blank=True, default='', editable=False, max_length=80)),
                ('referencia_externa', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('referencia_idempotencia', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('estado_sigedoc', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REGISTRADO', 'Registrado')], default='PENDIENTE', editable=False, max_length=12)),
                ('fecha_registro_sigedoc', models.DateTimeField(blank=True, editable=False, null=True)),
                ('anulado', models.BooleanField(default=False, editable=False)),
                ('fecha_anulacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, default='', editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('anulado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_anulados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL)),
                ('registrado_sigedoc_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_sigedoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de expediente',
                'verbose_name_plural': 'Registros de expedientes',
                'db_table': 'agenda',
                'ordering': ['-anio', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('accion', models.CharField(max_length=40)),
                ('datos', models.JSONField(default=dict)),
                ('motivo', models.TextField(blank=True, default='')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='agenda.agenda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ControlNumeracion',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=False)),
                ('anio_validado', models.PositiveSmallIntegerField(null=True)),
                ('ultimo_numero_libro', models.PositiveIntegerField(null=True)),
                ('fecha_confirmacion', models.DateTimeField(null=True)),
                ('confirmado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['anio', 'estado_sigedoc', 'anulado'], name='expediente_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('numero', 'anio'), name='expediente_numero_anio_unico'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sistema_origen', ''), _negated=True), ('referencia_externa__isnull', False)), fields=('sistema_origen', 'referencia_externa'), name='expediente_referencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_idempotencia__isnull', False)), fields=('sistema_origen', 'referencia_idempotencia'), name='expediente_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='expediente_numero_positivo'),
        ),
    ]
