# Generated by Django 5.2.17 on 2026-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('letra', models.CharField(max_length=10)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=12)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'agenda',
                'ordering': ['-numero'],
                'managed': False,
            },
        ),
    ]
