# Generated by Django 5.2.17 on 2026-10-05 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initialize_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativoAnual',
            fields=[
                ('anio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-anio', '-numero'], 'verbose_name': 'Registro de expediente', 'verbose_name_plural': 'Registros de expedientes'},
        ),
        migrations.CreateModel(
            name='AuditoriaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('accion', models.CharField(max_length=40)),
                ('datos', models.JSONField(default=dict)),
                ('motivo', models.TextField(blank=True, default='')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria', to='agenda.agenda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ControlNumeracion',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=False)),
                ('anio_validado', models.PositiveSmallIntegerField(null=True)),
                ('ultimo_numero_libro', models.PositiveIntegerField(null=True)),
                ('fecha_confirmacion', models.DateTimeField(null=True)),
                ('confirmado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
