# Generated by Django 5.2.17 on 2026-10-05 15:05

import agenda.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def prepare_legacy_schema(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, 'agenda')
    for name, value in constraints.items():
        if value.get('check') and value.get('columns') == ['origen']:
            schema_editor.execute(f'ALTER TABLE agenda DROP CONSTRAINT {schema_editor.quote_name(name)}')
    schema_editor.execute('ALTER TABLE agenda ALTER COLUMN numero DROP DEFAULT')


def preserve_history(apps, schema_editor):
    from zoneinfo import ZoneInfo
    from django.db.models import Max
    from django.utils import timezone
    db = schema_editor.connection.alias
    Registro = apps.get_model('agenda', 'Agenda')
    Counter = apps.get_model('agenda', 'CorrelativoAnual')
    Control = apps.get_model('agenda', 'ControlNumeracion')
    Audit = apps.get_model('agenda', 'AuditoriaExpediente')
    for row in Registro.objects.using(db).all().iterator():
        previous_origin = row.origen
        row.anio = row.fecha_hora.astimezone(ZoneInfo('America/Argentina/Buenos_Aires')).year
        row.created_at = row.fecha_hora
        row.updated_at = row.fecha_hora
        row.origen = {'manual': 'MESA_ENTRADA', 'automatico': 'SISTEMA_LEGADO'}.get(row.origen, row.origen)
        row.save(using=db, update_fields=['anio', 'created_at', 'updated_at', 'origen'])
        Audit.objects.using(db).create(registro=row, accion='MIGRAR_HISTORICO', datos={'origen_anterior': previous_origin, 'numero': row.numero, 'anio': row.anio}, motivo='Conservacion del registro historico de Agenda; autor y datos administrativos no disponibles.')
    for item in Registro.objects.using(db).values('anio').annotate(ultimo=Max('numero')):
        Counter.objects.using(db).create(anio=item['anio'], ultimo_numero=item['ultimo'])
    current_year = timezone.localdate().year
    counter, _ = Counter.objects.using(db).get_or_create(anio=current_year)
    # Conservar tambien el piso de la secuencia anterior, incluidos numeros consumidos.
    if schema_editor.connection.vendor == 'postgresql' and Registro.objects.using(db).filter(anio=current_year).exists():
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT to_regclass('agenda_numero_seq')")
            if cursor.fetchone()[0]:
                cursor.execute('SELECT last_value, is_called FROM agenda_numero_seq')
                value, called = cursor.fetchone()
                counter.ultimo_numero = max(counter.ultimo_numero, value if called else value - 1)
                counter.save(using=db)
    Control.objects.using(db).get_or_create(pk=1, defaults={'habilitado': False})


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_correlativoanual_alter_agenda_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(prepare_legacy_schema, migrations.RunPython.noop),
        migrations.AddField(
            model_name='agenda',
            name='anio',
            field=models.PositiveSmallIntegerField(default=agenda.models.anio_actual, editable=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='anulado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='anulado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='asunto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agenda',
            name='causante',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agenda',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='estado_sigedoc',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REGISTRADO', 'Registrado')], default='PENDIENTE', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecha_registro_sigedoc',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='referencia_idempotencia',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='registrado_sigedoc_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_sigedoc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='sistema_origen',
            field=models.CharField(blank=True, default='', editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agenda',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='letra',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='numero',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='origen',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='referencia_externa',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.RunPython(preserve_history),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['anio', 'estado_sigedoc', 'anulado'], name='expediente_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('numero', 'anio'), name='expediente_numero_anio_unico'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sistema_origen', ''), _negated=True), ('referencia_externa__isnull', False)), fields=('sistema_origen', 'referencia_externa'), name='expediente_referencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_idempotencia__isnull', False)), fields=('sistema_origen', 'referencia_idempotencia'), name='expediente_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='expediente_numero_positivo'),
        ),
    ]
