# Generated by Django 5.2.17 on 2026-10-06 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id_historico', models.PositiveBigIntegerField()),
                ('username_historico', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=40)),
                ('datos', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_usuarios', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_administrativa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
